/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CharityScheduledDistribution } from "./CharityScheduledDistribution";
export type { DistributionExecutor } from "./DistributionExecutor";
export type { DurationDonation } from "./DurationDonation";
export type { MockERC20 } from "./MockERC20";
export type { VolunteerVerification } from "./VolunteerVerification";
