/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VolunteerVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applications"
      | "charities"
      | "checkApplicationVerification"
      | "checkTimeWorkedVerification"
      | "owner"
      | "pause"
      | "paused"
      | "registerCharity"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "updateCharityStatus"
      | "verifyApplication"
      | "verifyTimeWorked"
      | "volunteerHours"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationVerified"
      | "CharityRegistered"
      | "CharityStatusUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "TimeWorkedVerified"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applications",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "charities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkApplicationVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTimeWorkedVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCharity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateCharityStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyApplication",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTimeWorked",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "volunteerHours",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "charities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkApplicationVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTimeWorkedVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCharity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCharityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTimeWorked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volunteerHours",
    data: BytesLike
  ): Result;
}

export namespace ApplicationVerifiedEvent {
  export type InputTuple = [
    applicationHash: BytesLike,
    applicant: AddressLike,
    charity: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    applicationHash: string,
    applicant: string,
    charity: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    applicationHash: string;
    applicant: string;
    charity: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CharityRegisteredEvent {
  export type InputTuple = [charity: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [charity: string, timestamp: bigint];
  export interface OutputObject {
    charity: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CharityStatusUpdatedEvent {
  export type InputTuple = [charity: AddressLike, isActive: boolean];
  export type OutputTuple = [charity: string, isActive: boolean];
  export interface OutputObject {
    charity: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeWorkedVerifiedEvent {
  export type InputTuple = [
    timeWorkedHash: BytesLike,
    volunteer: AddressLike,
    charity: AddressLike,
    totalHours: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    timeWorkedHash: string,
    volunteer: string,
    charity: string,
    totalHours: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    timeWorkedHash: string;
    volunteer: string;
    charity: string;
    totalHours: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VolunteerVerification extends BaseContract {
  connect(runner?: ContractRunner | null): VolunteerVerification;
  waitForDeployment(): Promise<this>;

  interface: VolunteerVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applications: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        applicationHash: string;
        applicant: string;
        charity: string;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  charities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, boolean] & {
        isRegistered: boolean;
        walletAddress: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  checkApplicationVerification: TypedContractMethod<
    [_applicationHash: BytesLike],
    [
      [boolean, string, string, bigint] & {
        isVerified: boolean;
        applicant: string;
        charity: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  checkTimeWorkedVerification: TypedContractMethod<
    [_timeWorkedHash: BytesLike],
    [
      [boolean, string, string, bigint, bigint] & {
        isVerified: boolean;
        volunteer: string;
        charity: string;
        totaltimeWorked: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerCharity: TypedContractMethod<
    [_charityAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateCharityStatus: TypedContractMethod<
    [_charityAddress: AddressLike, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  verifyApplication: TypedContractMethod<
    [_applicationHash: BytesLike, _applicant: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyTimeWorked: TypedContractMethod<
    [
      _timeWorkedHash: BytesLike,
      _volunteer: AddressLike,
      _timeWorked: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  volunteerHours: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        timeWorkedHash: string;
        volunteer: string;
        charity: string;
        totalHours: bigint;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        applicationHash: string;
        applicant: string;
        charity: string;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "charities"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, boolean] & {
        isRegistered: boolean;
        walletAddress: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkApplicationVerification"
  ): TypedContractMethod<
    [_applicationHash: BytesLike],
    [
      [boolean, string, string, bigint] & {
        isVerified: boolean;
        applicant: string;
        charity: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkTimeWorkedVerification"
  ): TypedContractMethod<
    [_timeWorkedHash: BytesLike],
    [
      [boolean, string, string, bigint, bigint] & {
        isVerified: boolean;
        volunteer: string;
        charity: string;
        totaltimeWorked: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerCharity"
  ): TypedContractMethod<[_charityAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCharityStatus"
  ): TypedContractMethod<
    [_charityAddress: AddressLike, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyApplication"
  ): TypedContractMethod<
    [_applicationHash: BytesLike, _applicant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyTimeWorked"
  ): TypedContractMethod<
    [
      _timeWorkedHash: BytesLike,
      _volunteer: AddressLike,
      _timeWorked: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "volunteerHours"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        timeWorkedHash: string;
        volunteer: string;
        charity: string;
        totalHours: bigint;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ApplicationVerified"
  ): TypedContractEvent<
    ApplicationVerifiedEvent.InputTuple,
    ApplicationVerifiedEvent.OutputTuple,
    ApplicationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "CharityRegistered"
  ): TypedContractEvent<
    CharityRegisteredEvent.InputTuple,
    CharityRegisteredEvent.OutputTuple,
    CharityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CharityStatusUpdated"
  ): TypedContractEvent<
    CharityStatusUpdatedEvent.InputTuple,
    CharityStatusUpdatedEvent.OutputTuple,
    CharityStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TimeWorkedVerified"
  ): TypedContractEvent<
    TimeWorkedVerifiedEvent.InputTuple,
    TimeWorkedVerifiedEvent.OutputTuple,
    TimeWorkedVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ApplicationVerified(bytes32,address,address,uint256)": TypedContractEvent<
      ApplicationVerifiedEvent.InputTuple,
      ApplicationVerifiedEvent.OutputTuple,
      ApplicationVerifiedEvent.OutputObject
    >;
    ApplicationVerified: TypedContractEvent<
      ApplicationVerifiedEvent.InputTuple,
      ApplicationVerifiedEvent.OutputTuple,
      ApplicationVerifiedEvent.OutputObject
    >;

    "CharityRegistered(address,uint256)": TypedContractEvent<
      CharityRegisteredEvent.InputTuple,
      CharityRegisteredEvent.OutputTuple,
      CharityRegisteredEvent.OutputObject
    >;
    CharityRegistered: TypedContractEvent<
      CharityRegisteredEvent.InputTuple,
      CharityRegisteredEvent.OutputTuple,
      CharityRegisteredEvent.OutputObject
    >;

    "CharityStatusUpdated(address,bool)": TypedContractEvent<
      CharityStatusUpdatedEvent.InputTuple,
      CharityStatusUpdatedEvent.OutputTuple,
      CharityStatusUpdatedEvent.OutputObject
    >;
    CharityStatusUpdated: TypedContractEvent<
      CharityStatusUpdatedEvent.InputTuple,
      CharityStatusUpdatedEvent.OutputTuple,
      CharityStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TimeWorkedVerified(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      TimeWorkedVerifiedEvent.InputTuple,
      TimeWorkedVerifiedEvent.OutputTuple,
      TimeWorkedVerifiedEvent.OutputObject
    >;
    TimeWorkedVerified: TypedContractEvent<
      TimeWorkedVerifiedEvent.InputTuple,
      TimeWorkedVerifiedEvent.OutputTuple,
      TimeWorkedVerifiedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
